// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public partial class Class
{
    public int ClassId { get; set; }

    public string ClassName { get; set; }

    public string ClassCode { get; set; }

    public string TeacherName { get; set; }

    public string RoomNumber { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? MaxStudents { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}