// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public partial class InventoryProduct
{
    public int InventoryId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public int? SystemAccountId { get; set; }

    public string WarehouseLocation { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string Notes { get; set; }

    public virtual Product Product { get; set; }

    public virtual SystemAccount SystemAccount { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}