// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string Unit { get; set; }

    public string Category { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<InventoryProduct> InventoryProducts { get; set; } = new List<InventoryProduct>();
}