// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public partial class Student
{
    public int StudentId { get; set; }

    public string StudentCode { get; set; }

    public string FullName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public int? ClassId { get; set; }

    public DateTime? EnrollmentDate { get; set; }

    public string Status { get; set; }

    public virtual Class Class { get; set; }
}