// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int InventoryId { get; set; }

    public int Quantity { get; set; }

    public int? SystemAccountId { get; set; }

    public string Status { get; set; }

    public virtual InventoryProduct Inventory { get; set; }

    public virtual SystemAccount SystemAccount { get; set; }
}